services:
  db:
    image: postgres
    container_name: database_django
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
